# AbdomenCT-1K baseline config
seed: 42
deterministic: true

data:
  root: ${data_root}
  train_list: ${work_dir}/splits/train.txt
  val_list: ${work_dir}/splits/val.txt
  # If you prefer to keep splits under dataset root, adjust above paths.
  num_workers: 4
  cache_rate: 0.0
  patch_size: [160, 160, 96]
  a_min: -150
  a_max: 250
  b_min: 0.0
  b_max: 1.0
  pixdim: [1.5, 1.5, 2.0]
  orientation: RAS
  num_classes: 5  # background + 4 organs (example) -> adjust to your label schema

trainer:
  max_epochs: 150
  val_every: 1
  amp: true
  grad_clip: 1.0

optim:
  lr: 2.0e-4
  weight_decay: 1.0e-5
  betas: [0.9, 0.999]
  scheduler:
    type: cosine
    t_max: 150
    eta_min: 1.0e-6

model:
  in_channels: 1
  out_channels: ${data.num_classes}
  channels: [32, 64, 128, 256, 512]
  strides:  [2, 2, 2, 2]
  dropout: 0.1

logging:
  work_dir: ${work_dir}
  ckpt_dir: ${work_dir}/checkpoints
  log_dir: ${work_dir}/tb
  results_csv: ${work_dir}/results.csv
